# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65\x64ge_server.proto\x12\x0b\x65\x64ge_server\"\x16\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x43\n\x06Server\x12\x39\n\x0b\x46orwardPass\x12\x13.edge_server.Tensor\x1a\x13.edge_server.Tensor\"\x00\x62\x06proto3')



_TENSOR = DESCRIPTOR.message_types_by_name['Tensor']
Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), {
  'DESCRIPTOR' : _TENSOR,
  '__module__' : 'edge_server_pb2'
  # @@protoc_insertion_point(class_scope:edge_server.Tensor)
  })
_sym_db.RegisterMessage(Tensor)

_SERVER = DESCRIPTOR.services_by_name['Server']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TENSOR._serialized_start=34
  _TENSOR._serialized_end=56
  _SERVER._serialized_start=58
  _SERVER._serialized_end=125
# @@protoc_insertion_point(module_scope)
